version: '3.8'

x-project-settings:
  name: "clear-closet"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./logs/backend:/logs

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend