# Generated by Django 4.2.13 on 2024-06-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_categoryapp', '0001_initial'),
        ('product_optionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('connect_url', models.TextField()),
                ('product_type', models.BooleanField(default=0)),
                ('product_status', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_categoryapp.productcategory')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_optionapp.productoption')),
            ],
        ),
    ]
