# Generated by Django 4.2.13 on 2024-07-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_categoryapp', '0001_initial'),
        ('product_optionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(default='노브랜드', max_length=255)),
                ('connect_url', models.TextField()),
                ('product_type', models.BooleanField(default=0)),
                ('product_status', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product_categoryapp.productcategory')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option', to='product_optionapp.productoption')),
            ],
        ),
    ]
