# Generated by Django 4.2.13 on 2024-07-10 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('image_type', models.IntegerField(default=0)),
                ('product', models.ManyToManyField(blank=True, related_name='product_images', to='productapp.product')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
